spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#logging:
#  level:
#    root: info
#  path: D:/log/coffee
#  file: log
#  默认日志文件名
#  file: log
#  默认日志路径
#  path: ./log
#  logback.xml路径，默认为classpath:logback.xml
#  config: ./logback.xml

#  config:
#server:
#  port: 8081
#  servlet:
#    context-path: /coffee
